#pragma once

// One dungeon floor and everything that builds or populates it.
//
// Levels are generated once and kept in the game's `levels` vector, never regenerated —
// revisiting a floor returns it exactly as you left it, kills and pickups included. The
// one deliberate exception is the player's minions, which follow the player between
// floors rather than being left behind (see move_minions_to_new_floor()).

#include <libtcod.hpp>

#include <utility>
#include <vector>

#include "actors.hpp"
#include "content.hpp"
#include "entity.hpp"
#include "map.hpp"
#include "projectile.hpp"

// Items lying on the floor, waiting to be picked up. Three near-identical structs rather
// than one tagged union, because each carries a different payload type; the Drop screen
// unifies them through ItemKind/ItemSlot instead (see actors.hpp).
struct GroundItem {
  int x, y;
  Weapon weapon;
};

struct GroundArmor {
  int x, y;
  Armor armor;
};

struct GroundPotion {
  int x, y;
  Potion potion;
};

// A monster glyph remembered at a tile after it's no longer in view — fog-of-war memory,
// but for monsters instead of terrain. Since monster AI moves things around, this may go
// stale (the monster shown there may no longer be there), same as remembering "there was
// a rat over there" doesn't guarantee it stayed put. That's by design.
struct RememberedMonster {
  int x, y;
  char glyph;
  tcod::ColorRGB color;
};

// One dungeon floor: its own map, monsters, items and in-flight spells.
struct Level {
  Map map;
  std::vector<Actor> monsters;  // hostiles *and* the player's minions; the player is not in here
  std::vector<GroundItem> items;
  std::vector<GroundArmor> armor_items;
  std::vector<GroundPotion> potions;
  std::vector<RememberedMonster> remembered_monsters;  // last-seen monster sightings, may go stale
  std::vector<Projectile> projectiles;                 // spells currently in flight on this floor
  int entry_x = 0;                                     // where the player arrives on this floor
  int entry_y = 0;
  bool has_stairs_up = false;  // whether entry_x/y doubles as a stairs-up tile (false on floor 1)
  int stairs_down_x = 0;
  int stairs_down_y = 0;
};

// Debug flag --fast-monsters: gives every hostile monster spawned one extra action per
// turn (Actor::extra_actions). A global rather than a parameter because it's read inside
// spawn_monster(), and floor 1 is generated by start_new_game() before main()'s normal
// argv loop runs — so it's set by a pre-scan at the very top of main() instead. Exists
// because no kMonsterTable row sets extra_actions today, and without it the monster half
// of the mechanic would have nothing to exercise it.
extern bool g_debug_fast_monsters;

// Assigns a stable id (see Actor::id) to a newly spawned monster or minion — a plain
// incrementing counter, unique for the life of the process. Ids are only ever compared
// for equality (MinionOrder::AttackTarget matching a specific enemy across turns), so
// there's no need to reset it on a new game; nothing outlives the Level that held the
// old ids anyway.
int allocate_actor_id();

// Builds a hostile monster from a table row. Every assignment is a straight copy into the
// identically-named Actor field — there's no monster-specific derivation left, which is
// the point: the result is an ordinary Actor that the combat, gear, potion and regen code
// can't tell apart from the player's.
Actor spawn_monster(const MonsterTemplate& tmpl, int x, int y);

// The minion counterpart of spawn_monster() — same shape; the only differences are the
// allegiance, the expiry timer, and having no XP bounty.
Actor spawn_minion(const MinionTemplate& tmpl, int x, int y);

// Spills everything an Actor was carrying onto its tile when it dies. Intrinsic gear
// (Fists, a Rat's Bite, bare skin) is part of the creature rather than equipment, so it
// leaves nothing behind — the same is_intrinsic rule that keeps the player's fists out of
// their own inventory. This is what makes a monster's inventory visible from the player's
// side: an Orc's Leather Armor and a Goblin Slinger's Dagger are the exact same items out
// of kArmorTable/kWeaponTable the floor spawns, so they can be picked up and used.
void drop_actor_gear(Level& level, const Actor& actor);

// Refreshes monster memory: records/updates a sighting for every monster currently in
// view, and forgets any remembered sighting whose tile we can currently see but which no
// longer has a monster on it (it moved on, died, or was never really there anymore).
void update_monster_memory(Level& level);

// Monster count grows gently with depth, capped so deep floors don't get absurd. Bosses
// are placed on top of this, not drawn from it.
int monster_count_for_depth(int depth);

// Picks a random walkable tile that isn't already in `occupied`. If require_room is true,
// corridor tiles are skipped too — used to keep stairs out of corridors. Hole tiles are
// excluded for free, since they aren't walkable.
std::pair<int, int> random_free_tile(const Map& map, const std::vector<std::pair<int, int>>& occupied,
                                     bool require_room = false);

// Finds a free (walkable, unoccupied) tile adjacent to (x,y) — the 8 neighbors, checked
// in a fixed order. Used to place a newly summoned minion next to the caster. Returns
// false (out_x/out_y untouched) if every neighbor is blocked.
bool free_adjacent_tile(const Map& map, const std::vector<Actor>& monsters, int x, int y, int& out_x, int& out_y);

// Builds and populates a fresh floor. depth is 1-indexed (matches the "Floor:N" HUD) and
// gates which monsters, weapons, armor and potions can spawn here, plus how many.
Level generate_level(int width, int height, bool has_stairs_up, int depth);

// Everything lying on the tile at (x,y), as ItemKind + an index into the matching
// Level vector. The ground counterpart of drop_slots(actor) in actors.hpp, and
// deliberately the same ItemSlot shape: one mechanism describes both "what you're
// carrying" and "what's at your feet", so the Drop and Pickup screens are the same
// kind of list over different sources.
//
// Order is weapons, then armor, then potions, each ascending — stable for as long as
// nothing mutates the Level, which is what lets the Pickup screen keep a selection as
// a parallel vector of bools rather than copying the items themselves.
//
// Unlike drop_slots(), index is never -1: nothing on the ground is "equipped".
std::vector<ItemSlot> ground_slots_at(const Level& level, int x, int y);
